Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.lgamSgn = exports.lgam = undefined;

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @file        lgam.js        Natural logarithm of Gamma function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * SYNOPSIS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * double x, y, lgam();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * y = lgam( x );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * DESCRIPTION:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Returns the base e (2.718...) logarithm of the absolute
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * value of the Gamma function of the argument.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * For arguments greater than 13, the logarithm of the Gamma
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * function is approximated by the logarithmic version of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Stirling's formula using a polynomial approximation of
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * degree 4. Arguments between -33 and +33 are reduced by
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * recurrence to the interval [2,3] of a rational approximation.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * The cosecant reflection formula is employed for arguments
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * less than -33.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Arguments greater than MAXLGM return NPY_INFINITY and an error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * message.  MAXLGM = 2.556348e305 for IEEE arithmetic.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * ACCURACY:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * arithmetic      domain        # trials     peak         rms
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *    IEEE    0, 3                 28000     5.4e-16     1.1e-16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *    IEEE    2.718, 2.556e305     40000     3.5e-16     8.3e-17
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * The error criterion was relative when the function magnitude
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * was greater than one but absolute when it was less than one.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * The following test used the relative error criterion, though
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * at certain points the relative error could be much higher than
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * indicated.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *    IEEE    -200, -4             10000     4.8e-16     1.3e-16
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Cephes Math Library Release 2.2:  July, 1992
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Copyright 1984, 1987, 1989, 1992 by Stephen L. Moshier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Ported to ECMAScript 2018
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Copyright (c) 2018, Kings Distributed Systems
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @author      KC Erb, kc@kcerb.com
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @date        April 2018
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */


var _polevl = require('../polevl.js');

var _constants = require('../constants.js');

var constants = _interopRequireWildcard(_constants);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

/* A[]: Stirling's formula expansion of log Gamma
* B[], C[]: log Gamma function between 2 and 3
*/
var A = [8.11614167470508450300E-4, -5.95061904284301438324E-4, 7.93650340457716943945E-4, -2.77777777730099687205E-3, 8.33333333333331927722E-2];

var B = [-1.37825152569120859100E3, -3.88016315134637840924E4, -3.31612992738871184744E5, -1.16237097492762307383E6, -1.72173700820839662146E6, -8.53555664245765465627E5];

var C = [
/* 1.00000000000000000000E0, */
-3.51815701436523470549E2, -1.70642106651881159223E4, -2.20528590553854454839E5, -1.13933444367982507207E6, -2.53252307177582951285E6, -2.01889141433532773231E6];

var MAXLGM = 2.556348e305;
var LOGPI = 1.14472988584940017414;

function lgam(x) {
  var _lgamSgn = lgamSgn(x),
      _lgamSgn2 = _slicedToArray(_lgamSgn, 1),
      res = _lgamSgn2[0];

  return res;
}

// Translator's note:
// returns array of [val, sign] to replace pointer functionality from original
function lgamSgn(x) {
  var p = void 0,
      q = void 0,
      u = void 0,
      w = void 0,
      z = void 0,
      i = void 0,
      sign = void 0;
  sign = 1;

  if (!isFinite(x)) return [x, sign];

  if (x < -34.0) {
    q = -x;

    var _lgamSgn3 = lgamSgn(q, sign);

    var _lgamSgn4 = _slicedToArray(_lgamSgn3, 2);

    w = _lgamSgn4[0];
    sign = _lgamSgn4[1];

    p = Math.floor(q);
    if (p === q) {
      // mtherr("lgam", SING);
      return [Infinity, sign];
    }
    i = p;
    if ((i & 1) === 0) sign = -1;else sign = 1;
    z = q - p;
    if (z > 0.5) {
      p += 1.0;
      z = p - q;
    }
    z = q * Math.sin(Math.PI * z);
    if (z === 0.0) {
      // mtherr("lgam", SING);
      return [Infinity, sign];
    }
    /*     z = log(NPY_PI) - log( z ) - w; */
    z = LOGPI - Math.log(z) - w;
    return [z, sign];
  }

  if (x < 13.0) {
    z = 1.0;
    p = 0.0;
    u = x;
    while (u >= 3.0) {
      p -= 1.0;
      u = x + p;
      z *= u;
    }
    while (u < 2.0) {
      if (u === 0.0) {
        // mtherr("lgam", SING);
        return [Infinity, sign];
      }
      z /= u;
      p += 1.0;
      u = x + p;
    }
    if (z < 0.0) {
      sign = -1;
      z = -z;
    } else {
      sign = 1;
    }
    if (u === 2.0) return [Math.log(z), sign];
    p -= 2.0;
    x = x + p;
    p = x * (0, _polevl.polevl)(x, B, 5) / (0, _polevl.p1evl)(x, C, 6);
    return [Math.log(z) + p, sign];
  }

  if (x > MAXLGM) {
    return [sign * Infinity, sign];
  }

  q = (x - 0.5) * Math.log(x) - x + constants.LS2PI;
  if (x > 1.0e8) return [q, sign];

  p = 1.0 / (x * x);
  if (x >= 1000.0) {
    q += ((7.9365079365079365079365e-4 * p - 2.7777777777777777777778e-3) * p + 0.0833333333333333333333) / x;
  } else {
    q += (0, _polevl.polevl)(p, A, 4) / x;
  }
  return [q, sign];
}

exports.lgam = lgam;
exports.lgamSgn = lgamSgn;